### ISSUE TITLE
No apt-fast or bc

### ISSUE THREAD

**Issue by TheRolfFR** [nanasess/setup-php#59]
Hello,

I have been testing your action in local with [act](https://github.com/nektos/act/) and discovered that their docker image didn't include apt-fast nor bc :
![image](https://user-images.githubusercontent.com/18086786/122024378-aaf0e780-cdc8-11eb-9eb4-b79db5261609.png)

You should definitely check if apt-fast and bc are install, else install them.

Thanks in advance,
TheRolf

**Comment by nanasess** [comment]
@TheRolfFR Welcome to setup-php, thanks for the detailed issue and feedback🙏
I would also like to support the act environment.

**Comment by nanasess** [comment]
@TheRolfFR 
I have created a branch to support act.
Please try to verify with `setup-php@act-support`.

```yaml
- name: Setup PHP
  uses: nanasess/setup-php@act-support
  with:
    php-version: '7.4'
```
