### ISSUE TITLE
Major version tag instead of master

### ISSUE THREAD

**Issue by anatawa12** [nanasess/setup-php#61]
Most GitHub official actions have tags to describe the latest release of specific major versions like `v3` however this action doesn't.
`@master` is not good because breaking changes in the feature can break our workflow in the feature. 
Could you make tags for major versions and increment major version only for breaking changes?

**Comment by nanasess** [comment]
@anatawa12 Thanks for the suggestion!
I have created a `@v3` branch.
Please try to verify with setup-php@v3

```yaml
- name: Setup PHP
  uses: nanasess/setup-php@v3
  with:
    php-version: '7.4'
```
